# Generated by Django 4.1.3 on 2022-11-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProgLang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_lang', models.CharField(max_length=60)),
                ('description_lang', models.TextField()),
                ('image', models.ImageField(upload_to='')),
                ('popular_lang_in_countries', models.CharField(choices=[('KYRGYZSTAN', 'KYRGYZSTAN'), ('GERMANY', 'GERMANY'), ('USA', 'USA'), ('RUSSIA', 'RUSSIA'), ('INDIA', 'INDIA'), ('JAPAN', 'JAPAN')], max_length=60)),
            ],
        ),
    ]
